version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
    example-workflow:
      jobs:
      - cypress/run:
          install-browsers: true
          start-command: 'npm run cypress'
          cypress-command: 'npx cypress run --browser chrome'