export const sampleCharacter = {
  "__typename": "Character",
  "id": "1",
  "name": "A-Bomb",
  "intelligence": 38,
  "strength": 100,
  "speed": 17,
  "durability": 80,
  "power": 24,
  "combat": 64,
  "fullName": "Richard Milhouse Jones",
  "placeOfBirth": "Scarsdale, Arizona",
  "publisher": "Marvel Comics",
  "alignment": "good",
  "gender": "Male",
  "race": "Human",
  "height": "6'8",
  "weight": "980 lb",
  "eyeColor": "Yellow",
  "hairColor": "No Hair",
  "groupAffiliation": "Hulk Family; Excelsior (sponsor), Avengers (honorary member); formerly partner of the Hulk, Captain America and Captain Marvel; Teen Brigade; ally of Rom",
  "image": "https://www.superherodb.com/pictures2/portraits/10/100/10060.jpg",
  "powerStatsWeightedAverage": 54
}